# Generated by Django 5.2.15 on 2026-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraseMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('autor', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Frases del mes',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mes', 'Mes'), ('año', 'Año')], default='diario', max_length=10)),
                ('categoria', models.CharField(choices=[('cuerpo', 'Cuerpo'), ('mente', 'Mente'), ('trabajo', 'Trabajo'), ('social', 'Social')], default='mente', max_length=10)),
                ('progreso', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
