# Generated by Django 5.2.15 on 2026-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=80)),
                ('relacion', models.CharField(blank=True, default='', max_length=60)),
                ('notas', models.CharField(blank=True, default='', max_length=300)),
                ('ultimo_contacto', models.DateField(blank=True, null=True)),
                ('contactado_semana', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Conexiones',
                'ordering': ['id'],
            },
        ),
    ]
