# Generated by Django 5.2.15 on 2026-06-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conexion',
            name='contactado_semana',
        ),
    ]
