# Generated by Django 5.2.15 on 2026-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('actividad', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('notas', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Actividades de agenda',
                'ordering': ['fecha', 'hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Autocuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('texto', models.CharField(blank=True, default='', max_length=200)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Autocuidados',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BloqueSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lun'), (1, 'Mar'), (2, 'Mié'), (3, 'Jue'), (4, 'Vie'), (5, 'Sáb'), (6, 'Dom')])),
                ('texto', models.CharField(max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Bloques de semana',
                'ordering': ['dia', 'orden', 'id'],
            },
        ),
    ]
