# Generated by Django 5.2.15 on 2026-06-12 23:00

import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccesoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('icono', models.CharField(default='spark', max_length=30)),
                ('color', models.CharField(default='#7c5cfc', max_length=9)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accesos rápidos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10)),
                ('acento', models.CharField(default='#7c5cfc', max_length=9)),
                ('densidad', models.CharField(choices=[('compact', 'Compacta'), ('regular', 'Regular'), ('comfy', 'Cómoda')], default='regular', max_length=10)),
                ('tema_espacial', models.BooleanField(default=False)),
                ('vista_agenda', models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes'), ('año', 'Año')], default='dia', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
