# Generated by Django 5.2.15 on 2026-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('sino', 'Sí / No'), ('cantidad', 'Cantidad')], default='cantidad', max_length=10)),
                ('unidad', models.CharField(blank=True, default='', max_length=15)),
                ('objetivo', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('paso', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('mejor_mas', models.BooleanField(default=True)),
                ('color', models.CharField(default='violet', max_length=15)),
                ('icono', models.CharField(default='spark', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hábitos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Registros de hábito',
                'ordering': ['fecha'],
            },
        ),
    ]
