# Generated by Django 5.2.15 on 2026-06-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrohabito',
            name='habito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='habitos.habito'),
        ),
        migrations.AddConstraint(
            model_name='registrohabito',
            constraint=models.UniqueConstraint(fields=('habito', 'fecha'), name='registro_unico_por_dia'),
        ),
    ]
